# Generated by Django 5.0 on 2024-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_masterproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='product_name',
            field=models.CharField(max_length=10),
        ),
    ]
